create table if not exists etilometro_risposte (
  id                      uuid        default gen_random_uuid() primary key,
  creato_il               timestamptz default now(),
  data_caricamento        date,
  asl                     text,
  data_evento             date,
  luogo_tipo              text,
  luogo_nome              text,
  tempo_da_bere           text,
  genere                  text,
  sesso_assegnato         text,
  eta                     text,
  patente                 text,
  patente_ritirata        text,
  trasporto_prima         text,
  trasporto_prima_altro   text,
  valore_atteso_range     text,
  valore_atteso_preciso   text,
  valore_rilevato_range   text,
  valore_rilevato_preciso text,
  trasporto_dopo          text,
  trasporto_dopo_altro    text,
  tipo_risposta           text,
  stima_consumo           integer,
  bevute_birra            integer,
  bevute_vino             integer,
  bevute_shot             integer,
  bevute_aperitivo        integer,
  ha_mangiato             text,
  ha_mangiato_da_quanto   text,
  sostanze                text[],
  sostanze_altro          text
);
